### ISSUE TITLE
Linktree Adaptation

### ISSUE THREAD

**Issue by noryev** [galaxyxone/openlinks#107]
Link your Linktree to an Openlinks account. 

Create an Openlinks based on a link.tree page. Create Openlinks links based on the same links that is within a Linktree page.

**Comment by galaxyxtwo** [comment]
As noted in closed issue- Linktree conversion/scraper feature #136 - Unfortunately, by making our Openlinks users authorize this scraping process, we will cause them to break the Linktree terms of service. Due to this issue, we will not be proceeding with this feature at this time. Further investigation is needed.
